name: ba-causal-inference-in-temporal-data
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - pytorch-lightning=1.6.0
  - numpy=1.21.5
  - networkx
  - scipy
  - matplotlib
  - seaborn
  - tqdm
  - imageio
  - ipywidgets
  - pandas
  - scikit-learn
  - pip
  - pip:
      - gdown
      - pykalman
